apiVersion: v1
kind: Service
metadata:
  name: {{ include "spotify-converter.fullname" . }}-backend-service
  labels:
    {{- include "spotify-converter.labels" . | nindent 4 }}
spec:
  type: {{ .Values.backend.service.type }}
  selector:
    {{- include "spotify-converter.backend.selectorLabels" . | nindent 4 }}
  ports:
    - port: {{ .Values.backend.port }}
      targetPort: {{ .Values.backend.port }}
      nodePort: {{ .Values.backend.service.nodePort }}
      protocol: TCP
