apiVersion: v1
kind: Service
metadata:
  name: {{ include "spotify-converter.fullname" . }}-frontend-service
  labels:
    {{- include "spotify-converter.labels" . | nindent 4 }}
spec:
  type: {{ .Values.frontend.service.type }}
  selector:
    {{- include "spotify-converter.frontend.selectorLabels" . | nindent 4 }}
  ports:
    - port: {{ .Values.frontend.port }}
      targetPort: {{ .Values.frontend.port }}
      nodePort: {{ .Values.frontend.service.nodePort }}
      protocol: TCP
